# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1742, 881)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 220, 381, 151))
        font = QtGui.QFont()
        font.setFamily("Pragmatica")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
" background-color:white;\n"
" border:2px;\n"
" border-radius:20;\n"
"}\n"
"QPushButton:hover{\n"
" background-color: #ffffff\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 430, 381, 141))
        font = QtGui.QFont()
        font.setFamily("Pragmatica")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
" background-color:white;\n"
" border:2px;\n"
" border-radius:20;\n"
"}\n"
"QPushButton:hover{\n"
" background-color: #ffffff\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 430, 381, 151))
        font = QtGui.QFont()
        font.setFamily("Pragmatica")
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
" background-color:white;\n"
" border:2px;\n"
" border-radius:20;\n"
"}\n"
"QPushButton:hover{\n"
" background-color: #ffffff\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(690, 220, 381, 151))
        font = QtGui.QFont()
        font.setFamily("Pragmatica")
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
" background-color:white;\n"
" border:2px;\n"
" border-radius:20;\n"
"}\n"
"QPushButton:hover{\n"
" background-color: #ffffff\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1270, 220, 381, 151))
        font = QtGui.QFont()
        font.setFamily("Pragmatica")
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
" background-color:white;\n"
" border:2px;\n"
" border-radius:20;\n"
"}\n"
"QPushButton:hover{\n"
" background-color: #ffffff\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 140, 1781, 41))
        self.lineEdit.setStyleSheet("background-color:#C6C6C6")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 1801, 141))
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:#000000;\n"
"color:#ffffff;\n"
"")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, 150, 1761, 641))
        self.label.setStyleSheet("background-color:#1e429b")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1270, 420, 381, 151))
        font = QtGui.QFont()
        font.setFamily("Pragmatica")
        font.setPointSize(16)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
" background-color:white;\n"
" border:2px;\n"
" border-radius:20;\n"
"}\n"
"QPushButton:hover{\n"
" background-color: #ffffff\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(850, 730, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Pragmatica")
        font.setPointSize(16)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
" background-color:white;\n"
" border:100px;\n"
" border-radius:35;\n"
"}\n"
"QPushButton:hover{\n"
" background-color: #FFFAFA\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(640, 20, 521, 101))
        self.label_3.setStyleSheet("image: url(:/newPrefix/logo-Point_B-white.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.lineEdit.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1742, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "База подрядчиков"))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить оплату"))
        self.pushButton_3.setText(_translate("MainWindow", "Проекты"))
        self.pushButton_4.setText(_translate("MainWindow", "Клиенты"))
        self.pushButton_5.setText(_translate("MainWindow", "База артистов"))
        self.pushButton_6.setText(_translate("MainWindow", "Склад"))
        self.pushButton_7.setText(_translate("MainWindow", "EXIT"))
import point_rc
